name: leaf_alarm_clock
version: 2.0.1
publish_to: none
description: 快速设置指定时间段之后的闹钟
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  intl: ^0.18.0
  numberpicker: ^2.1.2
  material_symbols_icons: ^4.2671.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
